### ISSUE TITLE
Feature request no images in timeline overview.

### ISSUE THREAD

**Issue by spacecabbie** [OleVik/grav-plugin-timeline#11]
Just like truncate option I suggest a default behavior of not loading any images from the event page.
With option to show content images from event page. 
for Example:
truncate_img: yes/no
This would be set in the timeline template page.

Note: where not talking about:
`media_order: *.png
image: *.png`
Those work like intended.

**Comment by OleVik** [comment]
This has been added as `truncate_image` in [v2.0.0-beta.1](https://github.com/OleVik/grav-plugin-timeline/releases/tag/v2.0.0-beta.1).
