### ISSUE TITLE
Integration into an active theme

### ISSUE THREAD

**Issue by romus33** [OleVik/grav-plugin-timeline#12]
Dear OleVik,
how to integrate timeline plugin into my active theme?

**Comment by OleVik** [comment]
Oh there are many ways, depending on what pieces of the Timeline you want to integrate where. You can adapt the [Timeline-template](https://github.com/OleVik/grav-plugin-timeline/blob/master/templates/timeline.html.twig) itself from within your theme to add menus or other elements, including overriding the empty `partials/timeline_header.html.twig` and `partials/timeline_footer.html.twig`.

You could also call the [`timeline`-block](https://github.com/OleVik/grav-plugin-timeline/blob/master/templates/timeline.html.twig#L26-L52) from that template using the [block-function](https://twig.symfony.com/doc/1.x/functions/block.html). As you'll see from the main template, it just uses a macro called [timeline_iteration](https://github.com/OleVik/grav-plugin-timeline/blob/master/templates/macros/timeline.html.twig), which uses [a function](https://github.com/OleVik/grav-plugin-timeline/blob/master/API/Content.php#L40) to build a hierarchical tree of Timelines and Events.

Could you expand on what type of integration you are looking for?

**Comment by ArmEagle** [comment]
I don't see any recent updates to this plugin, but a timeline was exactly what I was looking for, and I was wondering the exact same as @romus33 did. So I'm adding to this issue.

I recently started using Grav for the first time for a simple project. I simply picked a default theme: Quark and added your plugin. I added a timeline page and one event. When visiting that page any header and footer and possibly styling of the theme is gone.

Now I see that you completely rewrite the base html file.

This is the first plugin I'm looking at. But should a plugin not attempt to fill a content section and not overwrite a complete page? You allow filling the header and footer. But I think I'd want to extend the base html template of a theme and inject your stylesheets, scripts and content (and body class).

See the attached file which I placed in `user/themes/custom-quark/templates/timeline.html.twig` and where I just copy pasted some of your `timeline.html.twig`. I haven't figured out whether I can 'use' a file with the exact same name yet. Then I wouldn't have to resort to complete copy&paste. But if you had instead put all those bits in partials, then I could simply have included those from an extended base template.

[timeline.html.twig.txt](https://github.com/OleVik/grav-plugin-timeline/files/8639699/timeline.html.twig.txt)

**Comment by OleVik** [comment]
Yes, that is as intended; the plugin provides its own, theme-agnostic templates for reuse, as themes do not have universal components or structures. As such, the only reliable implementation is for themes to adapt the plugin, not the other way around - the styling and functionality of themes would in many cases affect what is provided by the plugin. No base is rewritten, its functionality stands alone.

As outlined in the previous comment, there are many ways to do this sort of implementation in a theme - or other plugin for that matter. You can use a file with the same name, but themes will override a template provided elsewhere by a plugin, as [detailed in README](https://github.com/OleVik/grav-plugin-timeline#adding-a-header-or-a-footer-or-customizing-templates).

To construct a timeline, you must necessarily implement the functionality of the [timeline-block](https://github.com/OleVik/grav-plugin-timeline/blob/v2.1.2/templates/timeline.html.twig#L25-L70). The HTML-structure and styling can be replaced, but the [iteration](https://github.com/OleVik/grav-plugin-timeline/blob/v2.1.2/templates/macros/timeline.html.twig) must occur to recursively iterate through a timeline's events. Doing this the other way, by implementing the theme into the timeline, is easier as the theme's styling can typically be reduced to simpler components that can be implemented in the templates supplied by the plugin.
