### ISSUE TITLE
Calling "timeline_iteration" on template is deprecated since version 1.28

### ISSUE THREAD

**Issue by romus33** [OleVik/grav-plugin-timeline#13]
Grav debugger gave me this message:
"message" => "Calling "timeline_iteration" on template "macros/timeline.html.twig" from template "macros/timeline.html.twig" is deprecated since version 1.28 and won't be supported anymore in 2.0."

How can fix it?

**Comment by OleVik** [comment]
This is a warning from Twig, which is rather poorly defined. The problem is known but won't become an issue until Grav implements Twig 2, which is a long ways off.
