### ISSUE TITLE
Issue using plugin

### ISSUE THREAD

**Issue by zisiyan** [OleVik/grav-plugin-timeline#4]
Hey, I'm new to Grav and I have been having a lot of trouble using plugins. 

I read through the readme.md but I still can't understand how you actually apply the plugin into my website. I have added the timeline.html.twig file into my templates file. 

I want to make a md file for it and add into my webpage, but I don't know how. 

Thanks for the help and sorry for any inconveniences. :(

**Comment by OleVik** [comment]
You don't need to add timeline.html.twig to your own templates, unless you want to change it, as the plugin makes them available for your installation of Grav. You'll instead want to do the following:

1. Create a Page for your Timeline, for example a folder like /user/pages/mytimeline
2. In this folder, create a file named `timeline.md`
3. Edit this file like any normal Page in Grav: Add some FrontMatter and Content ([example](https://raw.githubusercontent.com/OleVik/grav-skeleton-timeline/master/pages/timeline/timeline.md))
    - This is your actual Timeline, but not the Events within it
4. For each Event in the Timeline, create a subfolder, like /user/pages/mytimeline/myevent
5. In this folder, create a file named `timeline_event.md`
6. Edit this file like any normal Page in Grav too: Add FrontMatter and Content ([example](https://raw.githubusercontent.com/OleVik/grav-skeleton-timeline/master/pages/timeline/Dominate/Constantinian/consantius-ii/timeline_event.md))

For a full example, that you can download and edit or just browse through, take a look at the [Timeline Skeleton](https://github.com/OleVik/grav-skeleton-timeline) - especially the [Pages](https://github.com/OleVik/grav-skeleton-timeline/tree/master/pages/timeline) therein. The Skeleton also shows that you can nest Timelines within Timelines, as long as there are Events at the lowest level.

**Comment by zisiyan** [comment]
Thanks for the reply OleVik! :)

Sorry, still kind of confused with it's usage. I have created the folders with the markdown files in them. But when I'm at the admin dashboard, the timeline pages that I've created linked themselves to a random twig file, eg: blog.html.twig as its page template.

I'm currently using grav-skeleton-timer as my skeleton. So wanted to add the plugin in as one of my pages. Would appreciate it if you can explain how to do that. :)

**Comment by OleVik** [comment]
I ran through this:

1. Install latest Timer Skeleton, update Grav Core to v1.6.10.
2. Install latest stable Admin, v1.9.6, and latest stable Timeline, v1.3.1.
3. Go to Admin and create a new Page, using Timeline as the template:

![image](https://user-images.githubusercontent.com/974717/59564899-9bf5c400-904c-11e9-9f4c-614f0ed7b88f.png)

3a. Add a subtitle and some content.
3b. Save the Page:

![image](https://user-images.githubusercontent.com/974717/59564910-c8a9db80-904c-11e9-9ca7-a61b968535c8.png)

4. From the same Page (`http://timeline.local/admin/pages/my-timeline`), add a new Page, using Timeline Event as the template and "My Timeline" as Parent Page:

![image](https://user-images.githubusercontent.com/974717/59565003-00fde980-904e-11e9-8497-5203cc3c47b1.png)

4a. Add some content.
4b. Save the Page:

![image](https://user-images.githubusercontent.com/974717/59565020-39052c80-904e-11e9-982e-af19ac7edd40.png)

5. Visit the site, click the link "My Timeline" in the top navigation:

![image](https://user-images.githubusercontent.com/974717/59564958-67ced300-904d-11e9-9109-0bcd57692219.png)

6. The Timeline with Event(s) renders:

![image](https://user-images.githubusercontent.com/974717/59565037-5cc87280-904e-11e9-90c2-f5f8e52bc914.png)

In essence, make sure you choose the right Page Template when creating Timelines and Events in Admin. In the filesystem they will be `timeline.md` and `timeline_event.md` which correspond to `timeline.html.twig` and `timeline_event.html.twig`, respectively, which the Plugin makes available.

**Comment by zisiyan** [comment]
Thanks for the reply again!

I followed your steps, updating all the things needed. But when it comes to creating a page, I can't set my page template as timeline without copy pasting the timeline.html.twig file into my templates folder first... :/

![without](https://user-images.githubusercontent.com/46601389/59590846-7c7b9b80-911f-11e9-9fdb-7331a3e818de.jpg)

So I copied the file along with the ones in partials and macro into my templates folder, and I get this:

![withjpg](https://user-images.githubusercontent.com/46601389/59591045-e300b980-911f-11e9-8b23-92aec443c0e5.jpg)

So I select timeline as my page template, but the page does not contain the functions like from your pictures:

![inside](https://user-images.githubusercontent.com/46601389/59591201-2bb87280-9120-11e9-8d9a-69f80c621f70.jpg)

So to add the content, I clicked on expert mode and added my content there:

![edit](https://user-images.githubusercontent.com/46601389/59591848-5d7e0900-9121-11e9-9452-51b0d00e2a3f.jpg)

But when I load my webpage, this comes up:

![page](https://user-images.githubusercontent.com/46601389/59591723-14c65000-9121-11e9-937e-6b2974566df4.jpg)

As you can see, the title and the subtitle pops up, but the paragraph text doesn't. :/

Then I created my timeline_event.md page and placed my timeline.md as it's parent page. But it does not show up either, like the paragraph text. 

I think I missed out an important step. Would appreciate if you could walk me through this. :) And thanks again for helping me out with this!

**Comment by OleVik** [comment]
What version of Grav Core and Admin do you have installed?

**Comment by zisiyan** [comment]
The latest one which is Grav Core v1.6.10. and Admin Plugin v1.9.6

**Comment by OleVik** [comment]
What theme are you using? The blueprints or templates are not registering, which is likely due to some conflict with another plugin or theme. In a clean installation of Core v1.6.10, Admin v1.9.6, and Timeline v1.3.1, it works as expected.
