### ISSUE TITLE
Collapsible

### ISSUE THREAD

**Issue by marcoriopel** [OleVik/grav-plugin-timeline#5]
Hey! I'm new to Grav and this plugin looks awesome but it was wondering if there was a way to create a button that would collapse/expand the collection of events in the timeline. 

Thanks for your help!

**Comment by OleVik** [comment]
There is no built-in method as of now, nor is the timeline structured in a hierarchical-manner in the HTML rendered. However, each subordinate Timeline has the classes `.timeline-item.period`, and each of its Events have the classes `.timeline-item` with `.odd` or `.even`. As such, if you are familiar with JavaScript, you could collapse the Timeline - at any level - and its Events by just traversing the DOM between each `.period`.
